
platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'ChallengeMedicato' do
  pod 'Kingfisher'
  pod 'MBProgressHUD'
end

target 'KIFTests' do
  pod 'KIF', :configurations => ['Debug']
  pod 'KIF/IdentifierTests', :configurations => ['Debug']
end
